import Head from "next/head";
import Image from "next/image";
import styles from "../styles/home/Home.module.scss";

export default function Home() {
    return (<div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <main>
            <section id="carousel" className="section">
                <div
                    id="carouselExampleCaptions"
                    className="carousel carousel-dark slide"
                    data-bs-ride="carousel"
                >
                    <div className="carousel-indicators">
                        <button
                            type="button"
                            data-bs-target="#carouselExampleCaptions"
                            data-bs-slide-to="0"
                            className="active"
                            aria-current="true"
                            aria-label="Slide 1"
                        />
                        <button
                            type="button"
                            data-bs-target="#carouselExampleCaptions"
                            data-bs-slide-to="1"
                            aria-label="Slide 2"
                        />
                        <button
                            type="button"
                            data-bs-target="#carouselExampleCaptions"
                            data-bs-slide-to="2"
                            aria-label="Slide 3"
                        />
                    </div>
                    <div className="carousel-inner">
                        <div className="carousel-item active">
                <span className="carousel-img1">
                  <Image
                      layout="responsive"
                      width={300}
                      height={200}
                      src="/assets/home-page-cover-design-personal-accident.png"
                      alt="..."
                  />
                </span>
                            <div className="carousel-caption d-none d-md-block">
                                <h3 className="title">
                                    Baxtsiz hodisalardan <span className="text-orange text-bolder">sug&apos;urtalash</span>
                                </h3>
                                <h5>
                                    Some representative placeholder content for the first slide.
                                </h5>
                            </div>
                        </div>
                        <div className="carousel-item">
                <span className="carousel-img1">
                  <Image
                      layout="responsive"
                      width={300}
                      height={200}
                      src="/assets/car.webp"
                      alt="..."
                  />
                </span>
                            <div className="carousel-caption d-none d-md-block">
                                <h3 className="title">
                                    Transport vositalari sug&apos;urtasi
                                </h3>
                                <p>
                                    Some representative placeholder content for the second
                                    slide.
                                </p>
                            </div>
                        </div>
                        <div className="carousel-item">
                <span className="carousel-img1">
                  <Image
                      layout="responsive"
                      width={300}
                      height={200}
                      src="/assets/home7.png"
                      alt="..."
                  />
                </span>
                            <div className="carousel-caption d-none d-md-block">
                                <h3 className="title">
                                    Barcha xavflardan mulk sug&apos;urtasi
                                </h3>
                                <p>
                                    Some representative placeholder content for the third slide.
                                </p>
                            </div>
                        </div>
                    </div>
                    <button
                        className="carousel-control-prev"
                        type="button"
                        data-bs-target="#carouselExampleCaptions"
                        data-bs-slide="prev"
                    >
              <span
                  className="carousel-control-prev-icon"
                  aria-hidden="true"
              ></span>
                        <span className="visually-hidden">Previous</span>
                    </button>
                    <button
                        className="carousel-control-next"
                        type="button"
                        data-bs-target="#carouselExampleCaptions"
                        data-bs-slide="next"
                    >
              <span
                  className="carousel-control-next-icon"
                  aria-hidden="true"
              ></span>
                        <span className="visually-hidden">Next</span>
                    </button>
                </div>
            </section>

            <section id="insurances" className="section container p-5 text-center">
                <h2 className="title" data-aos="fade-up">
                    Sug`urtalar
                </h2>
                <h4 className="mb-4" data-aos="fade-up">
                    Yuridik shaxslar uchun
                </h4>
                <div className="row" data-aos="fade-up">
                    <div className="col-md-4">
                        <a href="#form">
                            <div className="card insurance-card">
                  <span
                      className="iconify card-img-top insurance-icon"
                      data-icon="dashicons:money-alt"
                  ></span>
                                <div className="card-body">
                                    <h5>Kredit sug&apos;urtasi</h5>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div className="col-md-4">
                        <a href="#form">
                            <div className="card insurance-card">
                  <span
                      className="iconify card-img-top insurance-icon"
                      data-icon="ic:baseline-emoji-transportation"
                  ></span>
                                <div className="card-body">
                                    <h5>Transport vositalari sug&apos;urtasi</h5>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div className="col-md-4">
                        <a href="#form">
                            <div className="card insurance-card">
                  <span
                      className="iconify card-img-top insurance-icon"
                      data-icon="bi:file-earmark-post"
                  ></span>
                                <div className="card-body">
                                    <h5>Javobgarlik sug&apos;urtasi</h5>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
                <h4 className="mt-5 mb-4" data-aos="fade-up">
                    Jismoniy shaxslar uchun
                </h4>
                <div className="row" data-aos="fade-up">
                    <div className="col-md-4">
                        <a href="#form">
                            <div className="card insurance-card">
                                <div className="card-body">
                    <span
                        className="iconify card-img-top insurance-icon"
                        data-icon="healthicons:accident-and-emergency-outline"
                    ></span>
                                    <h5>Baxtsiz hodisalardan sug&apos;urtalash</h5>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div className="col-md-4">
                        <a href="#form">
                            <div className="card insurance-card">
                  <span
                      className="iconify card-img-top insurance-icon"
                      data-icon="fa-solid:house-user"
                  ></span>
                                <div className="card-body">
                                    <h5>Barcha xavflardan mulk sug&apos;urtasi</h5>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div className="col-md-4">
                        <a href="#form">
                            <div className="card insurance-card">
                  <span
                      className="iconify card-img-top insurance-icon"
                      data-icon="feather:users"
                  ></span>
                                <div className="card-body">
                                    <h5>KASKO</h5>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </section>

            <section id="news" className="container py-5">
                <div className="row justify-content-center" data-aos="zoom-in">
                    <h2 className="title text-center">Yangiliklar</h2>
                    <div className="col-md-10">
                        <div className="card container-fluid">
                            <div className="row p-4">
                                <div className="col-md-5">
                                    <Image
                                        src="/assets/pexels-mikhail-nilov-7731402.jpg"
                                        className="card-img-top"
                                        alt=""
                                        layout="responsive"
                                        width={1000}
                                        height={500}
                                    />
                                </div>
                                <div className="col-md-7">
                                    <h4>Yangilik nomi</h4>
                                    <p>10.12.2021</p>
                                    <p>
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                                        Earum inventore eius odio dolorem quidem ipsam recusandae
                                        doloribus provident laboriosam non? Totam quo iusto
                                        provident culpa
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section id="about" className="container my-5">
                <h2 className="title">Aloqa</h2>
                <div className="row">
                    <div className="col-md-4 offset-md-1">
                        <p>
                            <strong>Telefon raqam:</strong> +998 94 277 98 11
                        </p>
                        <p>
                            <strong>Elektron pochta:</strong> test@mail.ru
                        </p>
                        <p>
                            <strong>Manzil:</strong> Lorem ipsum dolor sit amet consectetur
                            adipisicing elit. Dolorem, accusantium.
                        </p>
                    </div>
                    <div className="col-md-4 offset-md-1">
                        <iframe
                            src="https://yandex.ru/map-widget/v1/?um=constructor%3A8bbff61ddf7360057737b24ecc833856fe012b414eebb395515aa7f3977af83b&amp;source=constructor"
                            width="500"
                            height="400"
                            frameBorder="0"
                        ></iframe>
                    </div>
                </div>
            </section>

            <section id="form">
                <form action="" className="container">
                    <div className="row">
                        <div className="col-md-5 offset-md-1">
                            <div className="mb-3">
                                <label htmlFor="name" className="form-label">
                                    F. I. O. *
                                </label>
                                <input
                                    type="text"
                                    name="name"
                                    className="form-control"
                                    id="name"
                                />
                            </div>
                            <div className="mb-3">
                                <label htmlFor="mail" className="form-label">
                                    Elektron manzil *
                                </label>
                                <input
                                    type="text"
                                    name="mail"
                                    className="form-control"
                                    id="mail"
                                />
                            </div>
                            <div className="mb-3">
                                <label htmlFor="address" className="form-label">
                                    Tuman/shaxar *
                                </label>
                                <input
                                    type="text"
                                    name="address"
                                    className="form-control"
                                    id="address"
                                />
                            </div>
                            <div className="mb-3">
                                <label htmlFor="tell" className="form-label">
                                    Telefon raqam *
                                </label>
                                <input
                                    type="tel"
                                    name="tell"
                                    className="form-control"
                                    id="tell"
                                />
                            </div>
                        </div>
                        <div className="col-md-5">
                            <div className="mb-3">
                                <label htmlFor="queryType" className="form-label">
                                    So&apos;rov turi *
                                </label>
                                <select
                                    className="form-select"
                                    name="queryType"
                                    id="queryType"
                                >
                                    <option value="savol">Savol</option>
                                    <option value="shikoyat">Shikoyat</option>
                                    <option value="taklif">Taklif</option>
                                    <option value="boshqa">Boshqa</option>
                                </select>
                            </div>
                            <div className="mb-3">
                                <label htmlFor="message" className="form-label">
                                    Habar matni *
                                </label>
                                <textarea
                                    rows="5"
                                    className="form-control"
                                    id="message"
                                    name="message"
                                ></textarea>
                            </div>
                            <div className="mt-3 pt-3">
                                <button className="mt-1 btn btn-primary">Jo`natish</button>
                            </div>
                        </div>
                    </div>
                </form>
            </section>
        </main>
    </div>);
}
